<%@ Page Title="" Language="C#" MasterPageFile="~/AssessRite/Student/student.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="AssessRite.Student.Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h4>This is the sample Student page</h4>
    <p>
        What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras placerat massa sed orci malesuada, id volutpat sapien placerat. Praesent posuere augue sed feugiat blandit. Proin a scelerisque magna. Donec luctus, sapien id luctus interdum, purus lectus tristique odio, eget congue dui est a turpis. Maecenas tortor sapien, porttitor eget elementum a, tincidunt eget augue. Fusce efficitur metus id enim rutrum, ac condimentum risus faucibus. Donec magna arcu, euismod ac molestie ut, hendrerit nec lorem. Vivamus gravida tortor ligula, vel ornare neque vestibulum a. Donec pretium viverra leo sit amet tempor. Suspendisse molestie, massa et euismod gravida, eros orci bibendum eros, ac tincidunt risus lorem nec erat. Quisque eros augue, tincidunt egestas mattis cursus, consequat eget leo. Maecenas sed fermentum dui. Vestibulum quis eros quam.

Integer vel felis in nulla pellentesque ullamcorper vel aliquam turpis. Fusce viverra at ante a sodales. Aliquam ex ligula, volutpat sit amet felis ac, laoreet lacinia odio. Fusce sed neque convallis, posuere libero quis, vulputate mi. Sed luctus, turpis vitae ultrices viverra, magna eros pretium urna, nec cursus ante nisi nec nunc. Phasellus tincidunt enim et tristique pretium. Aenean tristique lobortis magna, id semper ligula.

Donec mi massa, rutrum non ante at, varius laoreet sem. Quisque id ultrices nulla. Integer et lectus urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras ut venenatis mauris. Aenean in placerat libero, id mattis justo. Phasellus sed consectetur mi, a mollis ex. Duis eu est interdum, sagittis justo a, pretium sapien. Aenean aliquam pharetra neque, quis accumsan sapien vulputate ut. Fusce eget porttitor justo. Nulla facilisi. Fusce gravida lacus eu lectus porta, quis ornare lectus consectetur.

Vivamus molestie porttitor semper. Aenean semper nibh leo, non hendrerit libero pharetra rutrum. Nunc fringilla, nisl id imperdiet vulputate, mi nibh eleifend nunc, ac dictum leo sem ut nunc. Nunc ut porta felis, vitae laoreet sem. Proin posuere nunc eu purus placerat ultricies. Donec dictum consectetur efficitur. Nulla vitae nibh vitae metus interdum congue non ut neque. Praesent malesuada justo quis magna lacinia pulvinar et molestie tellus. Maecenas in nisl eget erat consequat ullamcorper. Aliquam sed imperdiet diam, nec consequat purus. Praesent facilisis, eros eget convallis tempus, enim tellus consectetur augue, a malesuada dui ante scelerisque lacus. Curabitur rutrum elementum mauris sit amet porttitor.

Vivamus posuere laoreet ligula, in consequat felis scelerisque non. Aenean sagittis nulla ut felis tincidunt finibus. Pellentesque scelerisque tellus eget nibh ultricies, sed fringilla felis dictum. Aliquam nibh arcu, blandit pulvinar tellus sit amet, pulvinar vulputate nisi. Suspendisse potenti. Sed in metus feugiat, feugiat risus sit amet, aliquam sem. Suspendisse rhoncus dapibus felis non aliquam. Integer a dictum nulla, sed mollis leo. In erat dolor, consequat id mollis quis, dignissim et mi. Integer tristique interdum metus vel euismod. Donec ut egestas metus. In eu felis id sem dignissim faucibus. Nulla augue ipsum, volutpat at elit hendrerit, imperdiet commodo eros. Duis pulvinar molestie mauris, a consectetur augue rutrum rhoncus.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum lectus eros, eget aliquam elit sodales quis. Etiam rhoncus est at nunc euismod, sit amet dictum justo rutrum. Vestibulum venenatis feugiat dolor, tempus scelerisque orci convallis non. Pellentesque non ipsum imperdiet, bibendum velit id, molestie augue. Aliquam erat volutpat. Sed luctus, nunc vitae dignissim sollicitudin, magna mi sollicitudin ligula, non sollicitudin sapien ligula sed turpis. Duis vel ex sit amet eros placerat euismod at in lacus. Sed aliquet a nulla eu aliquam. Nunc in nibh massa. Aenean neque massa, sodales at ipsum non, cursus placerat lectus. Praesent sodales lacus et orci lobortis commodo et feugiat ligula. Aenean vitae ullamcorper velit, in venenatis ipsum. Etiam non mauris eget sapien condimentum cursus nec imperdiet erat. Fusce interdum volutpat nunc a consectetur. Etiam et scelerisque felis. Sed lacus enim, vulputate eu volutpat ac, finibus a odio.

Vivamus ac sagittis purus. Nulla sapien massa, consectetur at nisi ut, sodales sagittis libero. Fusce iaculis nisi ut nunc laoreet tristique. Ut porttitor, urna a pharetra facilisis, sem tortor pellentesque lectus, ac ullamcorper velit est at justo. Sed id leo lacus. Integer hendrerit pretium nulla, non ultricies justo fermentum a. Praesent placerat pulvinar imperdiet. Nullam pulvinar vehicula ante sed blandit.

Fusce at pretium mi, ac hendrerit leo. Vestibulum massa est, tincidunt at magna at, lacinia aliquet ipsum. Etiam facilisis eget eros nec venenatis. Etiam ac iaculis sapien. Nullam venenatis ac sapien quis fermentum. Fusce non scelerisque urna. Ut ipsum tortor, viverra varius sodales vel, placerat sed velit. Cras eros sem, dapibus eget scelerisque sed, maximus vehicula velit. Suspendisse eget sapien suscipit, dapibus lectus et, dapibus est. Curabitur sodales nulla non mollis viverra. Maecenas eu rhoncus tortor. Integer congue elementum dolor, vitae convallis leo tincidunt sed. Maecenas vel tincidunt elit.

Morbi scelerisque odio metus, ac ullamcorper ante auctor rutrum. Cras volutpat commodo turpis, ac euismod erat luctus in. Etiam velit orci, fermentum eu est eu, tristique maximus felis. Donec dolor metus, imperdiet quis nisi id, interdum gravida diam. Donec commodo dui eget elit dignissim, egestas cursus enim consectetur. Duis maximus eros sed ullamcorper condimentum. Sed a elementum mi. Pellentesque maximus magna at lacus bibendum, non tempus tellus semper. Aliquam erat volutpat. Donec vehicula dignissim nulla. Nunc lobortis ullamcorper blandit. Nam accumsan urna ac condimentum pellentesque. Nulla ac semper nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Aliquam erat volutpat. Suspendisse orci diam, egestas ac purus tincidunt, porta consequat diam. Aliquam a nibh purus. Nulla blandit ante eu turpis scelerisque maximus. Suspendisse sed consectetur ligula, et imperdiet orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam consequat dui et risus tincidunt, et interdum purus egestas. Mauris tempus pretium justo at tempus. Praesent lacinia est eget sagittis fermentum. Vestibulum quis pellentesque diam. In sit amet gravida lectus. Curabitur mollis, felis ac suscipit maximus, dolor turpis tincidunt sem, id efficitur turpis dolor quis libero. Cras risus sapien, elementum nec est ac, rutrum mattis nulla. Pellentesque suscipit bibendum pharetra.

In interdum porttitor mi, vel sodales turpis rhoncus non. Donec lacinia massa a augue mollis, accumsan hendrerit arcu blandit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec elementum ipsum nulla, a rutrum lorem blandit sit amet. Vestibulum metus dolor, ultrices non condimentum sed, ullamcorper eu turpis. Donec elit lectus, semper vitae libero at, mattis semper quam. Morbi sed diam ultrices, tempus ipsum at, accumsan eros. Praesent consectetur leo ac mollis scelerisque. Proin lorem est, sollicitudin nec fringilla sed, posuere quis velit. Sed id lacus eu libero fringilla volutpat vitae non dolor. In hac habitasse platea dictumst.
    </p>
</asp:Content>
